### ISSUE TITLE
Hosting migration

### ISSUE THREAD

**Issue by teamon** [tenex/rails-assets#312]
As a follow-up to #291.
## Current status: the future is bright! 🎆
- We are migrating rails-assets.org hosting into DigitalOcean (please try https://rails-assets.tenex.tech/)
- [Tenex](https://tenex.tech/) is taking over support and maintenance
### Questions still to be answered
- Who should own the rails-assets.org domain? (currently it is @teamon)
- Where should it be re-registered?
- What NS should it use? (currently Monterail's /cc @jandudulski)
### ToDo
- [x] Check email accounts for rails-assets.org (@teamon)
- [x] Point rails-assets.org to rails-assets.tenex.tech
- [x] https://github.com/rails-assets/rails-assets/issues/309

**Comment by jandudulski** [comment]
> What NS should it use?

If rails-assets will be hosted on DO than it would be probably much more convenient to move NS there too. But we can still keep it if that would be easier for Tenex :)

**Comment by thbar** [comment]
A couple of questions come to mind (I'm a new user of rails-assets, actually! Thanks for your work on this!):
- On "support and maintenance" provided by Tenex (thanks to them!): does this include securing the platform? Security of third-party dependencies is always an important consideration (MITM, tampering etc).
- Can Tenex comment on what is their current engagement (is it a "one year, to be renewed" scheme, or something different?) - I'm not asking specifically for something, except for visibility on what they are committing to, so that as a consultant I can provide informed advice to my clients.
- Should we as a community provide a way for companies (small, independent, or larger) to provide monetary backing to Tenex or other people involved in the project?

That's it for today!

**Comment by hut8** [comment]
- You're welcome! Obviously big thanks to Monterail for making it in the first place. If you have specific concerns about security, please bring it up. Tampering (at least while in transit) and MITM are taken care of by TLS, which we're using Let's Encrypt certificates for. Aside from that, what were you thinking? Securing things (and trying to break such security) is a hobby of mine as well as part of my job, so I would love to hear more about your thoughts.
- Our engagement is that we plan on maintaining this project -- we simply volunteered to host it when we read that it would otherwise close because we feel that it is a useful and worthwhile tool. There is no formal contract anywhere, but I'm sure you're familiar with open source projects like this. I would like to hear about what you tell your clients in regard to support for FOSS -- of course, most projects could fold at any time.
- We already have a donate button, from which we have received $20 so far and we also are sponsored very generously by Digital Ocean. Everything we collect from the button goes straight into hosting and other expenses for the project. Good suggestion :+1:

**Comment by hut8** [comment]
I set up the domain with algin.ns.cloudflare.com and chan.ns.cloudflare.com

The only part I'm worried about is the SSL stuff - we're using letsencrypt so we can't prove that we own the domain until it points to our server, which of course will cause pretty bad SSL issues because right now the cert is only good for `rails-assets.tenex.tech`.

@teamon since you have root on our server, if you would like (in order to avoid downtime) you could copy the SSL stuff into `/etc/letsencrypt/live/rails-assets.org/{fullchain.pem,privkey.pem}`. I'm fine with a few minutes of downtime as well if that's easier. Or, you could just have your server issue redirects, though I'm not sure how ACME deals with that.

Also, I closed #309

**Comment by matthewrudy** [comment]
Just to confirm @hut8, is the plan to keep the old domain continuously available
(once you resolve the SSL issues)?

Should I as an end user have to change my `Gemfile` to `source 'https://rails-assets.tenex.tech'`
or should I keep it pointing at rails-assets.org?

**Comment by tibastral** [comment]
That project is REALLY amazing, and we should keep it working. If you need anything, I can try to help (talking about it @ the next parisrb, or talk to my friends @heroku to host it for free for exemple).

**Comment by hut8** [comment]
@matthewrudy correct. If I were you, I would point it at rails-assets.tenex.tech simply because there will probably be downtime when the other domain is switched. We will keep rails-assets.tenex.tech up for a while.

**Comment by matthewrudy** [comment]
@hut8 thanks.
Have switched

``` ruby
source 'https://rails-assets.tenex.tech'
```

And once the change is complete
will switch back to

``` ruby
source 'https://rails-assets.org'
```

**Comment by matthewrudy** [comment]
@hut8 I had to revert this
as there's a bunch of versions missing on https://rails-assets.tenex.tech

eg.
- `angular-animate (1.5.0)`
- `datetimepicker (2.5.1)`

I clicked the `rebuild` button for those (and another one, I can't remember)
and waited a while,
but still not seeing it in https://rails-assets.tenex.tech/status
or in the gem list

**Comment by hut8** [comment]
@matthewrudy I apologize for that and it will not happen again :) Our sidekiq worker which actually builds the gems had died (I  have yet to debug why), and now it has been resurrected in such a way that we will be at the very least notified when it happens. Your gems should now be there.

@teamon can we get the DNS taken care of this week? That is a matter of some urgency now for obvious reasons. If you or someone from Monterail gets us DNS authorization transfer code, I can configure rails-assets.org on our registrar to use our nameserver (cloudflare), but still point it at your server until we're sure that no bad things will happen with SSL.

**Comment by jandudulski** [comment]
Hi,

to be honest I'm quite lost with the current status so I would just ask -
what is the status of ssl certs? Have they been copied to the new server? I
don't have access so I cannot check and Tymon is pretty busy with personal
issues so I have to deal with that on my own ;)

If certs are copied than I would like to set your ns server to rails-assets
domain so just give me a green light if ns is ready for that?

We would like to proceed with final domain transfer in April if that is not
the issue for you. Sorry for inconvenience.

best,

## 

[image: Monterail]

Jan Dudulski • Senior Developer

at Monterail http://monterail.com/, Ruby development and design agency with
love

skype: jan.dudulski.monterail • twitter: @yanoo_ http://twitter.com/yanoo_

**Comment by sheerun** [comment]
@jandudulski Are you asing me? It seems only Tymon has access

**Comment by hut8** [comment]
@jandudulski I don't have the certs. Can you get them to me and I can install them? The final domain transfer in April is fine.

**Comment by tibastral** [comment]
Why not cloudflare ?

**Comment by hut8** [comment]
### Quick update

Yesterday, the name server was pointed by @jandudulski to our nameserver (Cloudflare). I have updated the DNS and it is now pointed at our server. 

![Pretty busy server](http://i.imgur.com/MXlvA1O.png)

Traffic is most definitely flowing there, and the SSL seems to be correctly configured (there was probably zero downtime on either rails-assets.tenex.tech or rails-assets.org).

Our server is totally overloaded, but this is temporary. In the month or so since we copied all of the gems that were already built from the production rails-assets server, most have been updated, so it's going to just catch up with those and hopefully things will be okay. Until then, we're getting a few errors but we're monitoring it closely and will have everything performing well ASAP.

**Comment by hut8** [comment]
![Less overloaded](http://i.imgur.com/MxC6gdn.png)

Currently the load average is back down to ~ 0.2 so everything seems good. We are continuing to monitor the changeover.

**Comment by tibastral** [comment]
And for the servers, is it hosted by heroku for free or something ? Because I think we can arrange something with them.
- Thibaut

**Comment by hut8** [comment]
@tibastral Digital Ocean is sponsoring it, and we're accepting donations as well for maintenance. For details, see https://github.com/rails-assets/rails-assets/issues/291

**Comment by sheerun** [comment]
@hut8 Please use separate server for hosting and separate for building packages.

**Comment by hut8** [comment]
@sheerun I am doing this now. I can also get you access shortly.

**Comment by hut8** [comment]
@teamon Still around? The domain registration is the last piece we need to complete still.

**Comment by teamon** [comment]
Yep. I had a chat with Jan and I'll do my best to get this done this week :)

**Comment by teamon** [comment]
So, basically we need to transfer the domain ownership (surprising!)

@hut8 Few questions:
- where should the domain be transferred? (i.e. to which provider; now it's polish home.pl)
- who will be the legal owner of the domain (whois, invoices etc; now it's just me)
- who will be responsible for covering the cost of  the domain? (well, I did)

@jandudulski you can take a look at https://pomoc.home.pl/baza-wiedzy/transfer-domeny-z-home-pl-do-innego-operatora/

I'm expecting quite a bit of paperwork with home.pl but that's most probably all on my end ;)

**Comment by teamon** [comment]
(And I'm starting the process of getting AuthInfo right now)

**Comment by teamon** [comment]
...aaand I got AuthInfo code (I'm quite surprised they are working on the weekend)

**Comment by hut8** [comment]
Nice. Can you send that to liam@tenex.tech ? 

The transfer on your end should have been free (just to obtain the authorization code), but if it was not, I will reimburse you. Obviously we will pick up the bill for the domain going forward. The legal owner would be Tenex Developers.

Sound good?

**Comment by hut8** [comment]
I just got the auth code, gave it to namecheap, paid them money and now it looks like it's "Processing." :+1: Thanks @teamon !
